# Paths adapted for this repo (upstream targeted edument.perl6idea).
# WARNING: regeneration overwrites the vendored, HAND-EDITED machines in
# src/main/java/org/raku/comma/parsing/ -- see tools/README.md before running.
raku:
	raku -Ilib bin/p6g2idea generate perl6.pm6 ../../src/main/java/org/raku/comma/parsing/ Raku org.raku.comma.parsing

crotmp:
	raku -Ilib bin/p6g2idea generate crotmp.pm6 ../../src/main/java/org/raku/comma/cro/template/parsing CroTemplate org.raku.comma.cro.template.parsing
